title: Ilia Minkin
position: Postdoctoral Fellow
affiliation: Johns Hopkins University
email: iminkin2 (at) jh.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=tX1QJesAAAAJ
github_link: https://github.com/iminkin
linkedin: https://www.linkedin.com/in/ilia-minkin-9a199380
cv_link: 
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
